CC=gcc
GO=go build
CFLAGS=-Wall
DEBUGFLAGS=-D DEBUG
SOURCE=unfill.c
EXECUTABLE=unfill
GOSOURCE=fill.go
GOEXECUTABLE=fill

all:
	$(CC) $(CFLAGS) $(SOURCE) -o $(EXECUTABLE)
	$(GO) -o $(GOEXECUTABLE) $(GOSOURCE)

debug:
	$(CC) $(DEBUGFLAGS) $(CFLAGS) $(SOURCE) -o $(EXECUTABLE)
	$(GO) -o $(GOEXECUTABLE) $(GOSOURCE)

c:
	$(CC) $(DEBUGFLAGS) $(CFLAGS) $(SOURCE) -o $(EXECUTABLE)

go:
	$(GO) -o $(GOEXECUTABLE) $(GOSOURCE)

clean:
	rm -rf $(EXECUTABLE) $(GOEXECUTABLE)
